### ISSUE TITLE
Seperate settings file for production and development 

### ISSUE THREAD

**Issue by Abhimanue-rajesh** [SANTHOSH-MAMIDISETTI/robotics_club_management#5]
The system currently have the default settings.py file and you will need to change it to a module and and create production.py and development.py, this can help in production.

**Comment by SANTHOSH-MAMIDISETTI** [comment]
Hi @Abhimanue-rajesh,

Thank you for your feedback! I've successfully separated the settings into `production.py` and `development.py` modules, which should enhance the configuration for different environments. The changes have been committed and merged in pull request #8.

If you have any further suggestions or if there's anything else you'd like to discuss, please let me know!

Best,  
Santhosh
